### ISSUE TITLE
Cannot run pLisp at all.

### ISSUE THREAD

**Issue by heegaiximephoomeeghahyaiseekh** [shikantaza/pLisp#37]
Every time I try to start pLisp, I get the following error:

    <string>:147040: error: redefinition of '__g00000137'
    plisp: src/images.c:2149: recreate_native_fn_objects: Assertion `0' failed.
    Aborted

After messing around with GDB, I found that pLisp generates a gigantic C program in memory,
populated with definitions from an array called `json_native_fns`, and the source for `json_native_fns[28]` is identical to the source for `json_native_fns[5552]`. Unfortunately, I couldn't figure out how the global variable `json_native_fns` is populated, only that `load_from_image` is being called with a `file_name` argument of `"plisp.image"`.

I captured the string containing the C functions into a text file. I created one version with comments showing which index into `json_native_fns` contains each function, and another version without comments, which is exactly what pLisp passes to the C compiler:

[badcode.zip](https://github.com/shikantaza/pLisp/files/389824/badcode.zip)

**Comment by heegaiximephoomeeghahyaiseekh** [comment]
This is actually an error that I ran into back when I filed #28. It only happens if `plisp.image` resides in the current working directory when you start `pLisp`. You should fix pLisp so it doesn't fail so inexplicably.

**Comment by shikantaza** [comment]
I'm not sure whether I understand things correctly: pLisp looks for a file called 'plisp.image' in the current working directory, and if this file is not found, it emits the message that the default image file is not found, and proceeds to compile the core forms from the library source. If the file does exist in the current directory, things should work fine.

I think this might be due to an earlier version of the image file being present. Since things are in a state of flux, there is bound to be problems with the native code generated/contained in an earlier version of pLisp, so it's advisable to use the latest image file shipped.

When pLisp is built, the default image is stored in /usr/local/share/plisp. I do not know a way to force the user to use this file to start pLisp with (except indicate this in the documentation). Maybe I should create a .plisp directory in the user's home and store it there?

**Comment by shikantaza** [comment]
Closing the issue, as it's most likely a version mismatch between the pLisp image file and the pLisp executable.
